fix(release): Run after CI ⚙

diff --git a/.github/workflows/auto_release.yml b/.github/workflows/auto_release.yml
--- a/.github/workflows/auto_release.yml
+++ b/.github/workflows/auto_release.yml
@@ -4,12 +4,11 @@ name: Auto Releaser
 
 # Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
-  #push:
-  #  branches: [ main ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
+  workflow_run:
+    workflows: ["CI"]
+    branches: [main]
+    types: 
+      - completed
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -20,6 +19,13 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      - name: Workflow check (success)
+        if: ${{ github.event.workflow_run.conclusion == 'success' }}
+        run: echo "Proceeding with release 🎁"
+      - name: Workflow check (failure)
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: echo "Previous workflow failed, cancelling release ❌" && exit 1
+
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       - name: Install semantic-release plugins
